words = (
    "aardvark", "albatross", "alligator", "alpaca", "anaconda", "angelfish",
    "ant", "anteater", "antelope", "ape", "armadillo", "baboon", "badger",
    "barracuda", "bat", "bear", "beaver", "bee", "bison", "boar", "buffalo",
    "butterfly", "camel", "capybara", "caribou", "cassowary", "cat",
    "caterpillar", "catfish", "centipede", "cheetah", "chicken", "chimpanzee",
    "chinchilla", "cobra", "cockroach", "cod", "cougar", "cow", "coyote",
    "crab", "crane", "crocodile", "crow", "deer", "dingo", "dog", "dolphin",
    "donkey", "dragonfly", "duck", "eagle", "echidna", "eel", "elephant",
    "elk", "emu", "falcon", "ferret", "finch", "fish", "flamingo", "fly",
    "fox", "frog", "gazelle", "gecko", "gerbil", "giraffe", "goat", "goose",
    "gorilla", "grasshopper", "hamster", "hare", "hawk", "hedgehog", "hippo",
    "hornet", "horse", "hummingbird", "hyena", "ibex", "iguana", "jackal",
    "jaguar", "jellyfish", "kangaroo", "kingfisher", "koala", "komododragon",
    "ladybug", "lemur", "leopard", "lion", "lizard", "llama", "lobster",
    "lynx", "macaw", "magpie", "manatee", "mandrill", "meerkat", "mink",
    "mole", "mongoose", "monkey", "moose", "mosquito", "moth", "mouse",
    "mule", "narwhal", "newt", "octopus", "okapi", "opossum", "orangutan",
    "orca", "ostrich", "otter", "owl", "ox", "oyster", "panda", "panther",
    "parrot", "peacock", "pelican", "penguin", "pheasant", "pig",
    "platypus", "polarbear", "porcupine", "porpoise", "quail", "rabbit",
    "raccoon", "ram", "rat", "raven", "reindeer", "rhino", "rooster",
    "salamander", "salmon", "scorpion", "seahorse", "seal", "shark", "sheep",
    "skunk", "sloth", "snail", "snake", "sparrow", "spider", "squid",
    "squirrel", "starfish", "stingray", "swan", "tapir", "tarantula",
    "termite", "tiger", "toad", "toucan", "turkey", "turtle", "vulture",
    "walrus", "wasp", "weasel", "whale", "wolf", "wombat", "woodpecker",
    "yak", "zebra"
)